[store]
[store.primary]
connection = "postgresql://${postgres_user}:${postgres_pass}@${postgres_host}:5432/${postgres_db}?host=/var/run/postgresql"
pool_size = 10


[chains]
ingestor = "index_node_0"

[chains.mainnet]
shard = "primary"
provider = [ { label = "mainnet", url = "${ETHEREUM_RPC_0}", features = ["archive", "traces"] } ]

[deployment]
[[deployment.rule]]
indexers = [ "index_node_0" ]


[general]
query = "query_node_0"
